import React from "react";

const Trade = ({ trade }) => {
  const {
    id,
    currency,
    ticketnum,
    slprice,
    tpprice,
    slpips,
    tppips,
    rr,
    lotsize,
    commission,
    accumulate,
    trendd1,
    trendh4,
    trendh1,
    trendm15,
    avgtrend,
    d1close,
    h4close,
    h1close,
    m15close,
    d1prev,
    h4prev,
    h1prev,
    m15prev,
    d1200ema,
    h4200ema,
    h1200ema,
    m15200ema,
    d150sma,
    h450sma,
    h150sma,
    m1550sma,
    d18ema,
    h48ema,
    h18ema,
    m158ema,
    d120ema,
    h420ema,
    h120ema,
    m1520sma,
    d1env,
    h4env,
    h1env,
    m15env,
    beforeimage,
    afterimage,
    maxpips,
    profit,
    closed,
    closedat,
    closeprice,
    createdAt,
    updatedAt,
  } = trade;

  return (
    <>
      <div className="flex">{tppips}</div>
      <div className="flex">{currency}</div>
    </>
  );
};

export default Trade;

// {
//       id: 3,
//       currency: 'AUDJPY',
//       ticketnum: 1123,
//       slprice: '0.00',
//       tpprice: '0.00',
//       slpips: '12.00',
//       tppips: '222.00',
//       rr: '18.50',
//       lotsize: '0.00',
//       commission: '0.00',
//       accumulate: '5.50',
//       trendd1: '28.00',
//       trendh4: '77.00',
//       trendh1: '30.00',
//       trendm15: '0.00',
//       avgtrend: '19.25',
//       d1close: 'sell',
//       h4close: 'sell',
//       h1close: 'buy',
//       m15close: 'buy',
//       d1prev: 'buy',
//       h4prev: 'sell',
//       h1prev: 'buy',
//       m15prev: 'buy',
//       d1200ema: 'buy',
//       h4200ema: 'buy',
//       h1200ema: 'sell',
//       m15200ema: 'sell',
//       d150sma: 'buy',
//       h450sma: 'sell',
//       h150sma: 'sell',
//       m1550sma: 'sell',
//       d18ema: 'sell',
//       h48ema: 'sell',
//       h18ema: 'sell',
//       m158ema: 'sell',
//       d120ema: 'buy',
//       h420ema: 'sell',
//       h120ema: 'sell',
//       m1520sma: 'sell',
//       d1env: 'buy',
//       h4env: 'sell',
//       h1env: 'sell',
//       m15env: 'sell',
//       beforeimage: null,
//       afterimage: null,
//       maxpips: null,
//       profit: null,
//       closed: null,
//       closedat: null,
//       closeprice: null,
//       createdAt: '2022-05-01T20:17:42.164Z',
//       updatedAt: '2022-05-01T20:17:42.164Z'
//     }
